/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20ContarctSol from "./Erc20contarct.sol";
export { Erc20contract__factory } from "./Erc20contract__factory";
export { SaveERC20__factory } from "./SaveERC20__factory";
