/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20ContarctSol from "./Erc20contarct.sol";
export type { erc20ContarctSol };
export type { Erc20contract } from "./Erc20contract";
export type { SaveERC20 } from "./SaveERC20";
export * as factories from "./factories";
export type { Erc20contract } from "./Erc20contarct.sol/Erc20contract";
export { Erc20contract__factory } from "./factories/Erc20contarct.sol/Erc20contract__factory";
export { SaveERC20__factory } from "./factories/SaveERC20__factory";
